#!/bin/bash 

#Read a .gpx file(s) and write txt files containing the track points, the way points and track info in three different files.

#TODO: xmllint does not support namespaces, we should use another XML command line interpreter since we might have problems with some .gpx files
#with extensions. I have tested the scripts against garmin Base Camp, QLandKarte and wikiloc tracks, and it seems to work fine, but you might have
#problems with gpx files generated by other software.

#Have a look at gpxbabel binary, it might have functionality you might find interesting for your purposes.

#Help description
if [ "$1" == "-h" ]; then
  echo "Usage: `basename $0` [files]: Convert .gpx files to text files containing track points and way points."
  exit 0
fi

#Check we have xmllint command 
if ! type "xmllint" > /dev/null ; then
  echo "xmllint is required"
  exit 1
fi

#Output file prefix names
track_suffix="_track.txt"
wp_suffix="_waypoint.txt"

#File resuming all converted tracks
info_file="tracks_info.txt"

#number of files to be converted
num_files=0

#For each file on the arguments
for file in "$@"; do
    
    echo "Processing file " $(basename "$file") "..."
    track_file=$(basename "$file" .gpx)$track_suffix
    wp_file=$(basename "$file" .gpx)$wp_suffix
    num_files=$((num_files+1))
        
    #Remove extensions from gpx files, otherwise xmllint messes up with name spaces
    #Remove namespace references on the xml file, not supported by xmllin
    sed -e "s/xmlns/ignore/" "$file" | sed -e '/<extensions>/,/<\/extensions>/d' > temp.gpx
        
    #Check we only have one track per file
    if [ $(xmllint --xpath "count(//gpx/trk)" temp.gpx) -ne 1 ]; then
        echo "Only gpx files with one and only one track are supported." 1>&2
        exit 1
    fi
    
    #Get the file name, track name, date and any other useful information
    echo $(basename "$file") >> out_file_names.txt
    xmllint --xpath "//gpx/trk/name/text()" temp.gpx >> out_names.txt
    echo "" >> out_names.txt
    xmllint --xpath "//gpx/trk/trkseg/trkpt[1]/time/text()" temp.gpx >> out_timestamps.txt
    echo "" >> out_timestamps.txt
    
    #Get latitude and longitude, substitute attribute name by a new line and omit quotations
    xmllint --xpath "//gpx/trk/trkseg/trkpt/@lat" temp.gpx | sed "s/ lat=/\n/g" | sed "s/\"//g" | tail -n +2 > out_lat.tmp
    xmllint --xpath "//gpx/trk/trkseg/trkpt/@lon" temp.gpx | sed "s/ lon=/\n/g" | sed "s/\"//g" | tail -n +2 > out_lon.tmp

    #Get elevations and time stamps, substitute node names by new lines
    xmllint --xpath "//gpx/trk/trkseg/trkpt/ele" temp.gpx | sed -e "s/<\/ele>/\n/g" | sed "s/<ele>//g" > out_ele.tmp
    xmllint --xpath "//gpx/trk/trkseg/trkpt/time" temp.gpx | sed -e "s/<\/time>/\n/g" | sed "s/<time>//g" > out_time.tmp

    #Combine all columns in a file containing the track
    paste -d ";" out_lat.tmp out_lon.tmp out_ele.tmp out_time.tmp > "$track_file"

    #Print numbers of track points wrote
    echo $(xmllint --xpath "count(//gpx/trk/trkseg/trkpt)" temp.gpx) " track points wrote to $track_file"
    
    #remove temps
    rm -f out_lat.tmp out_lon.tmp out_ele.tmp out_time.tmp 

    #Check we have any waypoints
    if [ $(xmllint --xpath "count(//gpx/wpt)" temp.gpx) -ge 1 ]; then
                
        #Get latitude and longitude from waypoints
        xmllint --xpath "//gpx/wpt/@lat" temp.gpx | sed "s/ lat=/\n/g" | sed "s/\"//g" | tail -n +2 > out_wp_lat.tmp
        xmllint --xpath "//gpx/wpt/@lon" temp.gpx | sed "s/ lon=/\n/g" | sed "s/\"//g" | tail -n +2 > out_wp_lon.tmp

        #Get time and names
        xmllint --xpath "//gpx/wpt/time" temp.gpx | sed -e "s/<\/time>/\n/g" | sed "s/<time>//g" > out_wp_time.tmp
        xmllint --xpath "//gpx/wpt/name" temp.gpx | sed -e "s/<\/name>/\n/g" | sed "s/<name>//g" > out_wp_name.tmp

        #Combine all in a file containing the waypoints
        paste -d ";" out_wp_lat.tmp out_wp_lon.tmp out_wp_time.tmp out_wp_name.tmp > "$wp_file"
        
        #Print number of waypoints wrote
        echo $(xmllint --xpath "count(//gpx/wpt)" temp.gpx) " waypoints wrote to $wp_file"
        
        #Remove temps
        rm out_wp_lat.tmp out_wp_lon.tmp out_wp_name.tmp out_wp_time.tmp        
    fi
       
    #remove temps
    rm -f temp.gpx 
    
    #new line after each file
    echo
   
done

#Create info text files
seq $num_files > out_seq.txt
paste -d ";" out_seq.txt out_file_names.txt out_names.txt out_timestamps.txt > "$info_file"

#remove temporals
rm -f out_seq.txt out_file_names.txt out_names.txt out_timestamps.txt